version: '3.5'
services:
  boilerplate-angular-docker-portainer:
    container_name: Boilerplate-angular-docker-portainer
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - Boilerplate-angular-docker-portainer-volume:/app/node_modules
    ports:
      - 4200:4200
    stdin_open: true
    tty: true

volumes:
  Boilerplate-angular-docker-portainer-volume:
