name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  docker_portainer:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/angular-docker-portainer-CI.yml@master
    with:
      node_version: '18.x'